In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [45]:
#1
df=pd.read_csv('./student_multiple_features.csv')
df

   Student  StudyHours Attendance  PreviousMarks  FinalMarks
0    Aarav           2         70           38.0          42
1     Sita           3         75           45.0          50
2      Ram           4         80           52.0          58
3   Anisha           5         85           60.0          68
4    Rohan           6         90           68.0          78
5    Priya           7         92           75.0          85
6    Kiran           8         95           82.0          92
7    Nabin           4         78           55.0          60
8    Suman           5         82           63.0          70
9   Alisha           6         88           70.0          79
10  Bikash           7         91           78.0          87
11  Sabina           8         96           85.0          95
12  Roshan           3         72           48.0          52
13    Puja           9         98           90.0          98
14  Manish           5         86           66.0          73
15  Aakash           6     Absent           72.0          81
16    Rita           4         79           58.0          61
17   Deepa           7         90            NaN          89
18  Sanjay           8         97           88.0          96
19  Kushal           5         84           64.0          74

In [46]:
#2
df.head()
#3
df.tail()
#4
df.shape
#5
df.info()
#6
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student        20 non-null     str
 1   StudyHours     20 non-null     int64
 2   Attendance     20 non-null     str
 3   PreviousMarks  19 non-null     float64
 4   FinalMarks     20 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 932.0 bytes

       StudyHours  PreviousMarks  FinalMarks
count   20.000000      19.000000   20.000000
mean     5.600000      66.157895   74.400000
std      1.930367      14.788371   16.519207
min      2.000000      38.000000   42.000000
25%      4.000000      56.500000   60.750000
50%      5.500000      66.000000   76.000000
75%      7.000000      76.500000   87.500000
max      9.000000      90.000000   98.000000

In [47]:
#7.
df.isnull().sum()
df['PreviousMarks']=df['PreviousMarks'].fillna(df['PreviousMarks'].mean())
#here the Attendance is string and consist of a value Absent lets fill the value to zero
df['Attendance']=pd.to_numeric(df['Attendance'],errors ='coerce')
df["Attendance"]=df['Attendance'].fillna(df['Attendance']==0)
df
#8.
X=df[['StudyHours','Attendance','PreviousMarks']]
#9.
y=df['FinalMarks']
y

0     42
1     50
2     58
3     68
4     78
5     85
6     92
7     60
8     70
9     79
10    87
11    95
12    52
13    98
14    73
15    81
16    61
17    89
18    96
19    74
Name: FinalMarks, dtype: int64

In [54]:
#10.
X_train,X_test,y_train,y_test =train_test_split(
    X,y,test_size=0.2,random_state=42
)
X_train.count()

#11.
model=LinearRegression()
model.fit(X_train,y_train)

#12.
print('Intercept(bias)',model.intercept_)
print('Coefficient(weight) of StudyHours',model.coef_[0])
print('Coefficient(weight) of Attendance',model.coef_[1])
print('Coefficient(weight) of PreviousMarks',model.coef_[2])

Intercept(bias) -24.72656534333366
Coefficient(weight) of StudyHours 0.46955085570044847
Coefficient(weight) of Attendance 0.5471098161324165
Coefficient(weight) of PreviousMarks 0.7398940936343378

In [59]:
#13. 
new_student = pd.DataFrame({
    "StudyHours":[5,7,3],
    "Attendance":[90,95,75],
    "PreviousMarks":[70,82,55]
})
print(model.predict(new_student))

[78.65365894 91.20703886 58.40949858]