In [1]:
import pandas as pd

In [4]:
dd=pd.read_csv("../dataset/daraz_dataset.csv")

In [6]:
dd.iloc[:,2]

0        Anita Basnet
1        Pooja Basnet
2        Rohit Basnet
3        Pooja Sharma
4        Ram Adhikari
            ...
495        Sita Thapa
496      Ram Adhikari
497    Nabin Shrestha
498     Gita Shrestha
499    Rohit Adhikari
Name: CustomerName, Length: 500, dtype: str

In [8]:
dd.loc[:,"CustomerName"]

0        Anita Basnet
1        Pooja Basnet
2        Rohit Basnet
3        Pooja Sharma
4        Ram Adhikari
            ...
495        Sita Thapa
496      Ram Adhikari
497    Nabin Shrestha
498     Gita Shrestha
499    Rohit Adhikari
Name: CustomerName, Length: 500, dtype: str

In [11]:
dd[(dd["District"]=="Kathmandu") & (dd["PaymentMethod"]=="eSewa")]

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
147,DZ100148,2026-02-09,Nabin Thapa,39,Male,Kathmandu,Electronics,Smart Watch,2,39084,20,62534.4,eSewa,1,Processing
193,DZ100194,2026-06-14,Sita Shrestha,20,Male,Kathmandu,Fashion,Jacket,4,12361,20,39555.2,eSewa,4,Shipped
234,DZ100235,2026-05-28,Gita Shrestha,49,Female,Kathmandu,Home,Chair,3,22435,20,53844.0,eSewa,1,Returned
269,DZ100270,2026-05-07,Pooja Rai,29,Female,Kathmandu,Groceries,Biscuits,2,37203,5,70685.7,eSewa,1,Shipped
460,DZ100461,2026-05-27,Pooja Basnet,47,Female,Kathmandu,Fashion,Sneakers,3,40348,20,96835.2,eSewa,3,Cancelled

In [12]:
dd[(dd["Category"]=="Electronics")&(dd["Rating"]==5)]

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
57,DZ100058,2026-06-26,Nabin Basnet,31,Female,Biratnagar,Electronics,Bluetooth Speaker,3,8135,20,19524.00,Card,5,Processing
97,DZ100098,2026-02-02,Rohit Shrestha,55,Female,Dharan,Electronics,Power Bank,5,10021,0,50105.00,Card,5,Cancelled
180,DZ100181,2026-02-02,Anita Adhikari,18,Male,Biratnagar,Electronics,Bluetooth Speaker,5,26059,20,104236.00,IME Pay,5,Returned
205,DZ100206,2026-05-23,Ramesh Karki,24,Male,Lalitpur,Electronics,Bluetooth Speaker,4,29715,20,95088.00,COD,5,Delivered
271,DZ100272,2026-01-29,Ramesh Adhikari,41,Male,Itahari,Electronics,Bluetooth Speaker,5,46482,5,220789.50,IME Pay,5,Delivered
280,DZ100281,2026-02-09,Sita Rai,18,Female,Lalitpur,Electronics,USB Cable,5,36322,15,154368.50,COD,5,Returned
324,DZ100325,2026-05-08,Aarav Sharma,43,Female,Kathmandu,Electronics,USB Cable,4,21013,0,84052.00,Card,5,Delivered
329,DZ100330,2026-05-10,Gita Karki,18,Male,Chitwan,Electronics,USB Cable,4,43452,20,139046.40,IME Pay,5,Returned
355,DZ100356,2026-02-05,Pooja Basnet,34,Male,Lalitpur,Electronics,Bluetooth Speaker,5,5672,10,25524.00,eSewa,5,Delivered
377,DZ100378,2026-02-21,Ramesh Rai,30,Male,Nepalgunj,Electronics,Bluetooth Speaker,4,29068,0,116272.00,Card,5,Shipped
387,DZ100388,2026-01-09,Ramesh Rai,43,Male,Butwal,Electronics,Smart Watch,4,31647,20,101270.40,eSewa,5,Returned
395,DZ100396,2026-06-11,Gita Adhikari,28,Female,Dharan,Electronics,USB Cable,5,19077,15,81077.25,Card,5,Returned
484,DZ100485,2026-04-08,Bikash Karki,21,Male,Pokhara,Electronics,Smart Watch,1,45225,20,36180.00,Khalti,5,Delivered

In [15]:
dd.sort_values("TotalAmount",ascending=False)

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
375,DZ100376,2026-02-11,Asha Thapa,18,Male,Bhaktapur,Books,Notebook,5,45982,0,229910.00,IME Pay,5,Returned
271,DZ100272,2026-01-29,Ramesh Adhikari,41,Male,Itahari,Electronics,Bluetooth Speaker,5,46482,5,220789.50,IME Pay,5,Delivered
132,DZ100133,2026-02-04,Sita Rai,52,Female,Bhaktapur,Sports,Football,5,48481,10,218164.50,IME Pay,4,Shipped
435,DZ100436,2026-03-20,Nabin Rai,46,Male,Butwal,Home,Chair,5,43252,0,216260.00,eSewa,2,Shipped
472,DZ100473,2026-02-22,Sita Karki,42,Male,Kathmandu,Books,Python Basics,5,44649,5,212082.75,COD,1,Processing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,DZ100095,2026-03-02,Roshan Rai,19,Male,Biratnagar,Sports,Football,2,1273,10,2291.40,eSewa,2,Returned
492,DZ100493,2026-05-04,Kiran Sharma,55,Female,Lalitpur,Groceries,Coffee,1,2781,20,2224.80,Khalti,5,Cancelled
74,DZ100075,2026-03-18,Roshan Shrestha,49,Male,Butwal,Books,Notebook,3,468,10,1263.60,Card,4,Cancelled
195,DZ100196,2026-05-22,Manish Sharma,19,Female,Chitwan,Sports,Dumbbell,1,733,20,586.40,COD,1,Processing
27,DZ100028,2026-02-03,Rohit Basnet,46,Female,Chitwan,Books,Data Science 101,1,532,10,478.80,eSewa,1,Delivered