In [1]:
import pandas as pd

In [20]:
sd=pd.DataFrame({
    "salary": [1000,2000,3000,5000,7000,8000,9000,12000,50000000]
})
sd

     salary
0      1000
1      2000
2      3000
3      5000
4      7000
5      8000
6      9000
7     12000
8  50000000

In [21]:
Q1 =sd["salary"].quantile(0.25)
median =sd["salary"].quantile(0.5)
Q3 =sd["salary"].quantile(0.75)
IQR = Q3-Q1
upper_bound=Q3+1.5*IQR
lower_bound = Q1- 1.5*IQR
outliers= sd[(sd["salary"]<lower_bound) | (sd["salary"]>upper_bound)]
Q1
outliers

     salary
8  50000000

In [19]:
# u can remove,use median or mean, winsorization(caping)-> putting upper_bound or lower_bound in the data and most
#important always see the data in business pov