In [1]:
import pandas as pd

In [2]:
dd=pd.read_csv('../dataset/LMS_Dirty_Dataset.csv')
dd

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [9]:
# for course fee
Mean=dd['course_fee'].mean()
SD=dd['course_fee'].std()
dd['z_score_course_fee']=(dd['course_fee']-Mean)/SD
dd["z_score_course_fee"]
outlier = dd[(dd['z_score_course_fee']>3)|(dd['z_score_course_fee']<-3)]
outlier #id= 19

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,z_score_course_fee
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing,18.6392

In [13]:
Mean=dd['attendance_percent'].mean()
SD=dd['attendance_percent'].std()
dd['z_score_att']=(dd['attendance_percent']-Mean)/SD
dd["z_score_att"]
outlier = dd[(dd['z_score_att']>3)|(dd['z_score_att']<-3)]
outlier

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, z_score_course_fee, z_score_att]
Index: []

In [17]:
Mean=dd['assignment_score'].mean()
SD=dd['assignment_score'].std()
dd['z_score_assign']=(dd['assignment_score']-Mean)/SD
dd["z_score_assign"]
outlier = dd[(dd['z_score_assign']>3)|(dd['z_score_assign']<-3)]
outlier # value 1  id 39 ma

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,...,assignment_score,final_score,rating,mentor,phone,email,completion_status,z_score_course_fee,z_score_att,z_score_assign
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,...,-5,55,3,Manish,9856058698,user38@gmail.com,Ongoing,-0.001614,-0.009266,-3.481037

In [18]:
Mean=dd['final_score'].mean()
SD=dd['final_score'].std()
dd['z_score_fs']=(dd['final_score']-Mean)/SD
dd["z_score_fs"]
outlier = dd[(dd['z_score_fs']>3)|(dd['z_score_fs']<-3)]
outlier

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, z_score_course_fee, z_score_att, z_score_assign, z_score_fs]
Index: []

[0 rows x 22 columns]