In [1]:
import pandas as pd

In [2]:
dd= pd.read_csv('../dataset/LMS_Dirty_Dataset.csv')
dd

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [3]:
dd.head(10) #first 10 data 
dd.tail(10) #last 10 data ko
dd.shape #350 ota rows and 18 ota column raixa
dd.columns
dd.dtypes 
dd.describe() #numerical value ko matra

,student_id,age,course_fee,discount,attendance_percent,assignment_score,final_score,rating
count,350.000000,350.000000,350.000000,350.000000,349.000000,350.000000,350.000000,350.000000
mean,175.500000,26.174286,10085.711429,9.600000,70.154728,67.011429,65.011429,3.960000
std,101.180532,5.485686,53109.214627,7.929489,16.697929,20.686773,20.556718,0.817852
min,1.000000,17.000000,-5000.000000,0.000000,40.000000,-5.000000,30.000000,3.000000
25%,88.250000,21.000000,5000.000000,0.000000,58.000000,51.000000,47.000000,3.000000
50%,175.500000,27.000000,7000.000000,10.000000,70.000000,69.000000,65.000000,4.000000
75%,262.750000,31.000000,10000.000000,20.000000,83.000000,85.750000,82.000000,5.000000
max,350.000000,35.000000,999999.000000,20.000000,100.000000,100.000000,100.000000,5.000000

In [6]:
dd[dd.duplicated()].sum()
#duplicate data xaina so hamile remove garna parena
dd.info()
dd.isnull().sum() #euta only duplicate xa ie attendence_percent only
dd['attendance_percent']=dd['attendance_percent'].fillna(dd['attendance_percent'].mean())
dd.isnull().sum()#now nothing is null or NaN

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          350 non-null    int64
 1   student_name        350 non-null    str
 2   course              350 non-null    str
 3   city                350 non-null    str
 4   age                 350 non-null    int64
 5   gender              350 non-null    str
 6   enrollment_date     350 non-null    str
 7   course_fee          350 non-null    int64
 8   discount            350 non-null    int64
 9   payment_status      350 non-null    str
 10  attendance_percent  349 non-null    float64
 11  assignment_score    350 non-null    int64
 12  final_score         350 non-null    int64
 13  rating              350 non-null    int64
 14  mentor              350 non-null    str
 15  phone               350 non-null    str
 16  email               350 non-null    str
 17  completion_status   350 non-null    str
dtypes: float64(1), int64(7), str(10)
memory usage: 49.3 KB

student_id            0
student_name          0
course                0
city                  0
age                   0
gender                0
enrollment_date       0
course_fee            0
discount              0
payment_status        0
attendance_percent    0
assignment_score      0
final_score           0
rating                0
mentor                0
phone                 0
email                 0
completion_status     0
dtype: int64

In [12]:
#incorrect datatypes
dd['course_fee']=pd.to_numeric(dd["course_fee"], errors="coerce")
dd['age']=pd.to_numeric(dd["age"], errors="coerce")
dd['discount']=pd.to_numeric(dd["discount"], errors="coerce")
dd['assignment_score']=pd.to_numeric(dd["assignment_score"], errors="coerce")
dd['final_score']=pd.to_numeric(dd["final_score"], errors="coerce")
dd['rating']=pd.to_numeric(dd["rating"], errors="coerce")
dd['attendance_percent']=pd.to_numeric(dd["attendance_percent"], errors="coerce")

In [13]:
#incosistent text value
dd['city'].unique()
dd["city"] = dd["city"].replace("ktm", "Kathmandu")
dd['course'].unique()
dd['course']=dd['course'].replace('Pythn AI','Python with AI/ML')
dd['gender'].unique()# its ok
dd['payment_status'].unique()
dd['completion_status'].unique()
dd["city"] = dd["city"].str.strip().str.title()

In [14]:
#incorrect datatypes 
dd[(dd["age"] < 0)|(dd["age"] >100)]#--> correct xa
dd[dd['course_fee']<0] # 1 data xa 
dd['course_fee']=dd['course_fee'].abs() # kinaki 5000 xa aru data ko value fluuter ma
# dd[dd['course_fee']<0] now xaina
dd[dd['discount']<0]

dd[dd['attendance_percent']<0]
dd[(dd['assignment_score']<0) |(dd['assignment_score']>100)] #1 value in id 39
dd['assignment_score']=dd['assignment_score'].abs()
dd[dd['final_score']<0]#its ok
dd[(dd['rating']<0)|(dd['rating']>5)]

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [15]:
# age
Q1=dd['age'].quantile(0.25)
Q3=dd['age'].quantile(0.75)
IQR = Q3-Q1
lower_bound_age=Q1-1.5*IQR
upper_bound_age= Q3+ 1.5 *IQR
outlier = dd[(dd['age']<lower_bound_age)| (dd['age']>upper_bound_age)]
outlier

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [16]:
#course_fee
Q1=dd['course_fee'].quantile(0.25)
Q3=dd['course_fee'].quantile(0.75)
IQR = Q3-Q1
lower_bound_cour=Q1-1.5*IQR
upper_bound_cour= Q3+ 1.5 *IQR
outlier = dd[(dd['course_fee']<lower_bound_cour)| (dd['course_fee']>upper_bound_cour)]
outlier # values 1

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing

In [17]:
#discount
Q1=dd['discount'].quantile(0.25)
Q3=dd['discount'].quantile(0.75)
IQR = Q3-Q1
lower_bound_dis=Q1-1.5*IQR
upper_bound_dis= Q3+ 1.5 *IQR
outlier = dd[(dd['discount']<lower_bound_dis)| (dd['discount']>upper_bound_dis)]
outlier # no any values

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [18]:
#attendance_percent
Q1=dd['attendance_percent'].quantile(0.25)
Q3=dd['attendance_percent'].quantile(0.75)
IQR = Q3-Q1
lower_bound_att=Q1-1.5*IQR
upper_bound_att= Q3+ 1.5 *IQR
outlier = dd[(dd['attendance_percent']<lower_bound_att)| (dd['attendance_percent']>upper_bound_att)]
outlier  # no any values

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [19]:
## rating and final score donot need because we already tested range of them

In [24]:
dd_clean =dd[(dd['course_fee']>lower_bound_cour) &(dd['course_fee']<upper_bound_cour)]
#removed id  19

In [23]:
#clip method
dd['course_fee']=dd['course_fee'].clip(upper_bound_cour,lower_bound_cour)
dd.loc[dd['student_id']==9]

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed

In [26]:
Median =dd['course_fee'].median()
dd.loc[(dd['course_fee']<lower_bound_cour) | (dd['course_fee']>upper_bound_cour),'course_fee']=Median
dd.loc[dd['student_id']==9]#checking
dd.loc[dd['student_id']==19]#sabai thik xa

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,17500,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing

In [27]:
# for course fee
Mean=dd['course_fee'].mean()
SD=dd['course_fee'].std()
dd['z_score_course_fee']=(dd['course_fee']-Mean)/SD
dd["z_score_course_fee"]
outlier = dd[(dd['z_score_course_fee']>3)|(dd['z_score_course_fee']<-3)]
outlier #id= 19

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,z_score_course_fee
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,17500,10,Pending,41.0,75,51,4,Ishan,9803681891,user18@gmail.com,Ongoing,4.748258

In [28]:
Mean=dd['attendance_percent'].mean()
SD=dd['attendance_percent'].std()
dd['z_score_att']=(dd['attendance_percent']-Mean)/SD
dd["z_score_att"]
outlier = dd[(dd['z_score_att']>3)|(dd['z_score_att']<-3)]
outlier

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, z_score_course_fee, z_score_att]
Index: []

In [29]:
Mean=dd['assignment_score'].mean()
SD=dd['assignment_score'].std()
dd['z_score_assign']=(dd['assignment_score']-Mean)/SD
dd["z_score_assign"]
outlier = dd[(dd['z_score_assign']>3)|(dd['z_score_assign']<-3)]
outlier #   id 39 ma

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,...,assignment_score,final_score,rating,mentor,phone,email,completion_status,z_score_course_fee,z_score_att,z_score_assign
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,...,5,55,3,Manish,9856058698,user38@gmail.com,Ongoing,1.254445,-0.00928,-3.012568

In [30]:
Mean=dd['final_score'].mean()
SD=dd['final_score'].std()
dd['z_score_fs']=(dd['final_score']-Mean)/SD
dd["z_score_fs"]
outlier = dd[(dd['z_score_fs']>3)|(dd['z_score_fs']<-3)]
outlier

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, z_score_course_fee, z_score_att, z_score_assign, z_score_fs]
Index: []

[0 rows x 22 columns]

In [32]:
## previously maile sabai questions different different file ma gareko thiye but submission garna milena so 
##  maile sabai eutai file ma merge garera rakhnu paryo so code le kei sense nabanauna sakxa!!!!